spring:
  application:
    name: composite-service
  mvc:
    servlet:
      path: /composite-service
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8083

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
